// Code generated by protoc-gen-go.
// source: snowizard.proto
// DO NOT EDIT!

package snowizard

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type SnowizardRequest struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *SnowizardRequest) Reset()         { *m = SnowizardRequest{} }
func (m *SnowizardRequest) String() string { return proto.CompactTextString(m) }
func (*SnowizardRequest) ProtoMessage()    {}

type SnowizardResponse struct {
	Id               *int64 `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *SnowizardResponse) Reset()         { *m = SnowizardResponse{} }
func (m *SnowizardResponse) String() string { return proto.CompactTextString(m) }
func (*SnowizardResponse) ProtoMessage()    {}

func (m *SnowizardResponse) GetId() int64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func init() {
}
